trigger:
  branches:
    include:
      - "master"
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
    always: true
jobs:
  - job: release
    strategy:
      matrix:
        bullseye:
          containerImage: debian
          containerTag: bullseye
        buster:
          containerImage: debian
          containerTag: buster
        bionic:
          containerImage: ubuntu
          containerTag: bionic
        focal:
          containerImage: ubuntu
          containerTag: focal
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: Docker@2
        displayName: Build Docker Image
        inputs:
          command: build
          repository: "glaux/$(containerImage)"
          arguments: --build-arg IMAGE=$(containerImage):$(containerTag)
          tags: |
            $(containerTag)
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: push
          repository: "glaux/$(containerImage)"
          containerRegistry: glaux-registry
          tags: |
            $(containerTag)
