trigger:
  branches:
    include:
      - "master"
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
jobs:
  - job: release
    strategy:
      matrix:
        buster:
          containerImage: debian
          containerTag: buster
        bionic:
          containerImage: ubuntu
          containerTag: bionic
        focal:
          containerImage: ubuntu
          containerTag: focal
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: Docker@2
        displayName: Build Docker Image
        inputs:
          repository: "glaux/$(containerImage)"
          containerRegistry: glaux-registry
          tags: |
            $(containerTag)
